DROP DATABASE IF EXISTS AudioSistem;
CREATE DATABASE AudioSistem;
USE AudioSistem;

CREATE TABLE MESTO (
    IdMes INT PRIMARY KEY AUTO_INCREMENT,
    Mesto VARCHAR(100) NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE KORISNIK (
    IdKor INT PRIMARY KEY AUTO_INCREMENT,
    Ime VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Godiste INT NOT NULL,
    Pol ENUM('M', 'Z') NOT NULL,
    IdMes INT NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdMes) REFERENCES MESTO(IdMes)
);

CREATE TABLE KATEGORIJA (
    IdKat INT PRIMARY KEY AUTO_INCREMENT,
    Naziv VARCHAR(100) NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIO (
    IdAud INT PRIMARY KEY AUTO_INCREMENT,
    Naziv VARCHAR(200) NOT NULL,
    Trajanje INT NOT NULL, -- sekunde
    IdKor INT NOT NULL, -- vlasnik
    Datum DATE NOT NULL,
    Vreme TIME NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor)
);

CREATE TABLE AUDIO_KATEGORIJA (
    IdAud INT NOT NULL,
    IdKat INT NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IdAud, IdKat),
    FOREIGN KEY (IdAud) REFERENCES AUDIO(IdAud),
    FOREIGN KEY (IdKat) REFERENCES KATEGORIJA(IdKat)
);

CREATE TABLE PAKET (
    IdPak INT PRIMARY KEY AUTO_INCREMENT,
    MesecnaCena DECIMAL(10,2) NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRETPLATA (
    IdPre INT PRIMARY KEY AUTO_INCREMENT,
    IdKor INT NOT NULL,
    IdPak INT NOT NULL,
    Datum DATE NOT NULL,
    Vreme TIME NOT NULL,
    PlacenaCena DECIMAL(10,2) NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor),
    FOREIGN KEY (IdPak) REFERENCES PAKET(IdPak)
);

CREATE TABLE SLUSANJE (
    IdSlu INT PRIMARY KEY AUTO_INCREMENT,
    IdAud INT NOT NULL,
    IdKor INT NOT NULL, -- slusalac
    Datum DATE NOT NULL,
    Vreme TIME NOT NULL,
    PocetniSekund INT NOT NULL,
    TrajanjeUSekundama INT NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdAud) REFERENCES AUDIO(IdAud),
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor)
);

CREATE TABLE OCENA (
    IdKor INT NOT NULL,
    IdAud INT NOT NULL,
    Ocena INT NOT NULL CHECK (Ocena BETWEEN 1 AND 5),
    Datum DATE NOT NULL,
    Vreme TIME NOT NULL,
    VremeUnosa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IdKor, IdAud),
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor),
    FOREIGN KEY (IdAud) REFERENCES AUDIO(IdAud)
);

-- Trigeri

DELIMITER $$

CREATE TRIGGER provera_aktivne_pretplate
BEFORE INSERT ON PRETPLATA
FOR EACH ROW
BEGIN
    DECLARE broj_aktivnih INT;

    SELECT COUNT(*) INTO broj_aktivnih
    FROM PRETPLATA
    WHERE IdKor = NEW.IdKor
      AND ABS(TIMESTAMPDIFF(DAY, TIMESTAMP(Datum, Vreme), TIMESTAMP(NEW.Datum, NEW.Vreme))) < 30;

    IF broj_aktivnih > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Korisnik vec ima aktivnu pretplatu. Pretplata traje 30 dana.';
    END IF;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER provera_cene_pretplate
BEFORE INSERT ON PRETPLATA
FOR EACH ROW
BEGIN
    DECLARE trenutna_cena DECIMAL(10,2);

    SELECT MesecnaCena INTO trenutna_cena
    FROM PAKET
    WHERE IdPak = NEW.IdPak;

    IF NEW.PlacenaCena != trenutna_cena THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Placena cena mora biti jednaka trenutnoj ceni paketa.';
    END IF;
END$$

DELIMITER ;
